services:
  - type: web
    name: telegram-music-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    region: oregon
    autoDeploy: true
    
